# Generated by Django 5.2.14 on 2026-05-10 17:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_initial'),
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailySalesReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True)),
                ('product_name', models.CharField(max_length=200)),
                ('total_units_sold', models.PositiveIntegerField(default=0)),
                ('total_revenue', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('order_count', models.PositiveIntegerField(default=0)),
                ('batch_index', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='daily_reports', to='products.product')),
            ],
            options={
                'ordering': ['-date', '-total_revenue'],
                'indexes': [models.Index(fields=['date'], name='orders_dail_date_9ca9d5_idx')],
                'unique_together': {('date', 'product')},
            },
        ),
    ]
